import styles from "./Methane.module.css";

import { motion, useAnimation, useInView, useScroll } from "framer-motion";
import { letterAnimation, textAnimation } from "../../../../animations/text";
import { AnimatedText } from "../../../../components/AnimatedText";
import { useEffect, useRef } from "react";
import clsx from "clsx";

import MethaneImage from "../../../../assets/images/methane.png";

export const MethanePage = () => {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  const inView = useInView(containerRef, { margin: "-400px" });
  const controls = useAnimation();

  const { scrollYProgress } = useScroll({
    target: wrapperRef,
  });

  useEffect(() => {
    console.log(inView, controls);

    if (inView) {
      controls.start("visible");
    }
  }, [controls, inView]);

  return (
    <section className={clsx(styles.container)} ref={wrapperRef}>
      <motion.img
        style={{
          opacity: scrollYProgress,
        }}
        src={MethaneImage}
        alt="Methane image"
        className={clsx(styles.methane_image)}
      />
      <div className={clsx(styles.content_wrapper)} ref={containerRef}>
        <motion.h3
          initial="hidden"
          animate={controls}
          variants={letterAnimation}
          className="heading1"
        >
          Methane
        </motion.h3>
        <motion.p
          initial="hidden"
          animate={controls}
          variants={textAnimation}
          className={clsx(styles.content)}
        >
          <AnimatedText
            segments={[
              "In the heart of Earth's natural cycles, lay a seemingly innocuous gas called methane. It had been present since time immemorial, generated by both natural processes and human activities. ",
              "Methane, a byproduct of decay and digestion in the animal kingdom, emerged from swamps, wetlands, and the bellies of livestock. Yet, it was also born from human endeavors—agriculture, landfills, and the extraction and use of fossil fuels.",
            ]}
            className={clsx(styles.content_container)}
          />
        </motion.p>
      </div>
      <div className={clsx(styles.content_wrapper)} ref={containerRef}>
        <motion.h3
          initial="hidden"
          animate={controls}
          variants={letterAnimation}
          className="heading1"
        >
          72x
        </motion.h3>
        <motion.p
          initial="hidden"
          animate={controls}
          variants={textAnimation}
          className={clsx(styles.content)}
        >
          <AnimatedText
            segments={[
              "In the heart of Earth's natural cycles, lay a seemingly innocuous gas called methane. It had been present since time immemorial, generated by both natural processes and human activities. ",
              "Methane, a byproduct of decay and digestion in the animal kingdom, emerged from swamps, wetlands, and the bellies of livestock. Yet, it was also born from human endeavors—agriculture, landfills, and the extraction and use of fossil fuels.",
            ]}
            className={clsx(styles.content_container)}
          />
        </motion.p>
      </div>
    </section>
  );
};
